flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')


flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)



# Routes are what we type into our browser, to find specific pages
# Routes take us to specific information
# URL: Uniform Resource Location
# The "/" is the root page of a website


# The @ symbol is a decorator. It is a way to add more functionality to an existing function
# @app.route = additional functionality, e.g. auto-called, and directed to webbrowser
# def hello_world() is the base function
@main.route("/")
@main.route("/home")     # Using a 2nd route for the same page
def home():
    try:
        #  request.args.get('page', 1) refers to the ?page=1 in the browser url
        page = request.args.get('page', 1, type=int)
        posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    except:
        posts = ""
    return render_template('home.html', posts=posts, title='Hanoi')



# The 'about page' route
@main.route("/about")
def about():
    return render_template('about.html', title='About')


flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required

from flaskblog import db
from flaskblog.models import Post

from flaskblog.posts.forms import PostForm


posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data,
                    author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))

    return render_template('create_post.html',
                           title='New Post',
                           form=form,
                           legend='New post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post has been updated!', 'info')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content

    form.title.data = post.title
    form.content.data = post.content
    return render_template('create_post.html',
                           title=f"Update: {post.title}",
                           post=post,
                           form=form,
                           legend='Update post')



@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'info')
    return redirect(url_for('main.home'))


flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post

from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccoutForm

from flaskblog.users.utils import save_picture

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash(f'You are already registered and logged in', 'info')
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=hashed_pw)
        db.session.add(user)
        db.session.commit()

        flash(f'Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html',
                           title='Register',
                           form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash(f'You are already logged in', 'info')
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)

            next_page = request.args.get('next')    # Reference to login?next=%2Faccount

            # The 'success' argument is taken directly from bootstrap css
            flash(f'You are logged in with {form.email.data}', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))

        else:
            # The 'danger' argument is taken directly from bootstrap css
            flash(f'Login unsuccessful. Please check email and password', 'danger')

    return render_template('login.html',
                           title='Login',
                           form=form)


@users.route("/logout")
@login_required
def logout():
    # logout extension already knows the credentials of a user already logged in
    logout_user()
    if session.get('was_once_logged_in'):
        del session['was_already_logged_in']
    flash(f'You have logged out successfully', 'info')
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccoutForm()

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account information has been updated', 'success')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    # 'image_file' reference to database column for User

    return render_template('account.html',
                           title='Account',
                           image_file=image_file,
                           form=form)



@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=2)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/all_users")
@login_required
def all_users():
    users = User.query.all()
    return render_template('all_users.html', users=users)


@users.route("/all_users/<string:user_email>/delete_user", methods=['GET', 'POST'])
@login_required
def delete_user(user_email):
    flash(f"Deleted - {user_email} - ", 'warning')


    return redirect(url_for('main.home'))



flaskblog/templates/about.html

{% extends "layout.html" %}

{% block content %}

    <h1>The English blog about page</h1>

{% endblock content %}

flaskblog/templates/account.html

{% extends "layout.html" %}

{% block content %}

    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>

        <!-- Place form for update account here -->

        <!-- Encoding type specifier is reference to picture upload, so form handles text and images -->
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}         <!-- hidden_tag provides csrf token // cross-site request forgery token-->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Account info
                </legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid feedback">
                            {% for error in form.username.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid feedback">
                            {% for error in form.email.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            </br><span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>


    </div>

{% endblock content %}

flaskblog/templates/all_users.html
{% extends "layout.html" %}

{% block content %}

<div class="content-section">
    {% for user in users %}
        <span>{{ user }}</span>
        <span>{{ user.email }}</span><br>
        <a class="btn btn-danger btn-sm mt-1" href="{{url_for('users.delete_user', user_email=user.email)}}">Delete</a>
        </br></br>
    {% endfor %}
</div>

{% endblock content %}

flaskblog/templates/create_post.html

<!-- Used for Create post, and for update post -->

{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                {{ legend }}
            </legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg mb-2") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>

    </form>

</div>


{% endblock content %}

flaskblog/templates/home.html

{% extends "layout.html" %}

{% block content %}

    {% if current_user.username %}
        <h2>Logged in as: {{ current_user.username }}</h2>
    {% else %}
        <h2>Not logged in</h2>
    {% endif %}

    {% for post in posts.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        </div>
    </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
                                        left_current=1, right_current=1) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {%  endfor %}

{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required Bootstrap meta reference and CDN link for CSS --->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>English Blog - {{ title }} </title>
    {% else %}
        <title>English Blog</title>
    {% endif %}

</head>
<body>

    <header class="site-handler">
        <nav class="navbar navbar-extend-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Practice English long-form</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <!-- Lefthand-side-->
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                    </div>

                    <!-- Righthand-side-->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
			    {% if current_user.username == 'jj' %}
                                <a class="nav-item nav-link" href="{{ url_for('users.all_users') }}">Something</a>
                            {% endif %}
                        {% else %}
                            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        {% endif %}

                    </div>

                </div>

            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                <!-- 'with_categories' refers to the bootstrap styles -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our sidebar</h3>
                    <p class="text-muted">Some text that can be changed later
                        <ul>
                            <li>Latest posts</li>
                            <li>Announcements</li>
                            <li>Calendars</li>
                            <li>Etc</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>

</body>
</html>

flaskblog/templates/login.html

{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}         <!-- hidden_tag provides csrf token // cross-site request forgery token-->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Login
                </legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid feedback">
                            {% for error in form.email.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid feedback">
                            {% for error in form.password.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
<!--
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
-->
            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>

            <small class="text-muted ml-2">
                <a href="#">Forgot password?</a>
            </small>

        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up</a>
        </small>
    </div>

{% endblock content %}

flaskblog/templates/post.html

{% extends "layout.html" %}

{% block content %}

<h1>Your post</h1>

    <article class="media content-section">
          <img class="rounded-circle article-img"
               src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
              <div class="article-metadata">
                  <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                  <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>

                    {% if post.author.username == current_user.username %}
                        <div>
                            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>

                            <!-- Bootstrap recent changes: data-bs-toggle="modal" data-bs-target="#deleteModal" -->
                            <button type="button" class="btn btn-danger btn-sm mt-1 mb-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>

                        </div>

                    {% endif %}

              </div>
              <h2 class="article-title">{{ post.title }}</h2>
              <p class="article-content">{{ post.content }}</p>
          </div>
    </article>

    <!-- Modal deleteModal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Certain to delete post?</h5>
 <!--           <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>  -->
          </div>
          <div class="modal-body">
            Click off the modal to go back
          </div>
          <div class="modal-footer">
<!--            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>  -->

            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>

          </div>
        </div>
      </div>
    </div>

{% endblock content %}

flaskblog/templates/register.html

{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}         <!-- hidden_tag provides csrf token // cross-site request forgery token-->
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">
                    Join today
                </legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid feedback">
                            {% for error in form.username.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid feedback">
                            {% for error in form.email.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid feedback">
                            {% for error in form.password.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>
                                    {{ error }}
                                </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
            </fieldset>
            <div class="form-group mt-2">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign in</a>
        </small>
    </div>

{% endblock content %}

flaskblog/templates/user_posts.html

{% extends "layout.html" %}

{% block content %}

    <h2 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h2>

    {% for post in posts.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        </div>
    </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
                                        left_current=1, right_current=1) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {%  endfor %}

{% endblock content %}